language: node_js
node_js:
  - 10
cache: npm
script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local-dir: public
env:
  global:
    secure: Oyt/bAgaj+yqO+ULvl5CmrrnnW+7uwkm0vo7P7lz6EpXi534rkLi0mxbmI+bk1jKAmrVWqYCDCNbqcXcuM9aKCF6s2ZI1ADtj9puPU2wBOFYnhJH912oZsOtoqJxYQttWHdcFOEWr3K6LcVPMw9lXrArotiML83so+segcnn3HLikAvH1mxIX7AG1+tNaC3cpFhMfeXuT3Av1mz814fkTHuRF660Is5WimZfiVrafQC2yvJX2jb00CW2oipn8ZPmj7wQDVW2EpX1xwu6TIMyJwzqmTbqusz9HRcYXein8SDmffP7EIwgBvYBBk8MX/fCG5qAR/nQlUzSEzta96t8Twg85ojKmSBdyF4H8umOqu2wAtsNUxebZmMHz1z2L1w5V3uskOk32KTGUZ6noDvikaKulKl1epqj1oMObz9UtngM7wMVnS//h5raHtJo4YbYPX3RZgm6TeJe/bgLLJV9t9lcp4+I49/guhLdrMUjqb2TX7U7LP0o3TWQExtZD23auQygAdkQrAbi7UC8p0GfqmdgltxvrGFpqdVdlmSCyQr+mpN62JzdZAA55K1aM5QFTm59RNCDVOjORbrHF17azn7IKDANMFOKM/6kwh0boCiE5REGmmwEz9TJqjNfIdDr8yfVgDJHV3Of3mCqrBbW1cg0kgXuL9eUHsxCjKnPr8M=
