language: node_js
node_js:
  - 10
  
cache: yarn

script:
  - yarn
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 4f7806a47fa82950052270357937fc7a4c129375  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master